/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  KigzagDeployerLT,
  KigzagDeployerLTInterface,
} from "../KigzagDeployerLT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "creatorfactory",
        type: "address",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_creatorSaleFeeNative",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_creatorSaleFeeUSD",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "dao",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vault",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class KigzagDeployerLT__factory {
  static readonly abi = _abi;
  static createInterface(): KigzagDeployerLTInterface {
    return new utils.Interface(_abi) as KigzagDeployerLTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KigzagDeployerLT {
    return new Contract(address, _abi, signerOrProvider) as KigzagDeployerLT;
  }
}
