var banks = [
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Canara Bank",
  "Central Bank of India",
  "Indian Bank",
  "Indian Overseas Bank",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "State Bank of India",
  "UCO Bank",
  "Union Bank of India",
  "Axis Bank Ltd.",
  "Bandhan Bank Ltd.",
  "CSB Bank Ltd.",
  "City Union Bank Ltd.",
  "DCB Bank Ltd.",
  "Dhanlaxmi Bank Ltd.",
  "Federal Bank Ltd.",
  "HDFC Bank Ltd",
  "ICICI Bank Ltd.",
  "Induslnd Bank Ltd",
  "IDFC First Bank Ltd.",
  "Jammu & Kashmir Bank Ltd.",
  "Karnataka Bank Ltd.",
  "Karur Vysya Bank Ltd.",
  "Kotak Mahindra Bank Ltd",
  "Nainital Bank Ltd.",
  "RBL Bank Ltd.",
  "South Indian Bank Ltd.",
  "Tamilnad Mercantile Bank Ltd.",
  "YES Bank Ltd.",
  "IDBI Bank Ltd.",
  "Au Small Finance Bank Limited",
  "Capital Small Finance Bank Limited",
  "Equitas Small Finance Bank Limited",
  "Suryoday Small Finance Bank Limited",
  "Ujjivan Small Finance Bank Limited",
  "Utkarsh Small Finance Bank Limited",
  "ESAF Small Finance Bank Limited",
  "Fincare Small Finance Bank Limited",
  "Jana Small Finance Bank Limited",
  "North East Small Finance Bank Limited",
  "Shivalik Small Finance Bank Limited",
];

export default banks;